DROP TABLE IF EXISTS nodes;
DROP TABLE IF EXISTS tags;

CREATE TABLE nodes(
    id BIGINT NOT NULL PRIMARY KEY,
    user VARCHAR(256) NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    lat DOUBLE PRECISION NOT NULL
);

CREATE TABLE tags(
    node_id BIGINT NOT NULL REFERENCES nodes(id),
    key VARCHAR(256) NOT NULL,
    value VARCHAR(256) NOT NULL,
    PRIMARY KEY (node_id, key)
);